name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose -- testing_programs/cargo_test.mlogs
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: target/release/slimlog
